server:
  port: 8001

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

docker:
  host: tcp://127.0.0.1:2375

minio:
  inner-url: 10.8.6.60:9000
  url: http://10.8.6.60:9000
  access-key: afK2BE5BSWvayIw546b2
  secret-key: ZRITpJds2V3lQyDb3T3t3GyA383G7npr32p9zk9x
  bucket-name: algorithm

template:
  path: /etc/imp/algorithm-scheduling/template.json

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 珠海横乐医学科技有限公司 allen.huang@hanglok-tech.cn
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: true
    enable-group: true
  cors: false
  production: false
  basic:
    enable: true
    username: hanglok
    password: hanglok8888