server:
  port: 8443
  ssl:
    key-store: classpath:mykeystore.p12
    key-store-password: hanglok
    keyStoreType: PKCS12
    keyAlias: myalias

spring:
  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 3000MB
  datasource:
    url: jdbc:mysql://10.8.6.34:3366/algorithm_scheduling_dev
    username: root
    password: hanglok8888
    driver-class-name: com.mysql.cj.jdbc.Driver

callback:
  url: https://10.8.6.34:8088/assemble/callback

docker:
  host: tcp://10.8.6.34:2375

minio:
  inner-url: 10.8.6.60:9000
  url: http://10.8.6.60:9000
  access-key: afK2BE5BSWvayIw546b2
  secret-key: ZRITpJds2V3lQyDb3T3t3GyA383G7npr32p9zk9x
  bucket-name: algorithm
  enable-public-network: false
  public-url: http://163.179.121.34:18000/minio

#template:
#  path: algorithm-scheduling-server/src/main/resources/template1.json

token: a9c6af52-d8af-4933-884a-79fddd3519c9

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'v1.0.0'
      paths-to-match: '/**'
      packages-to-scan: cn.hanglok.algoSched.controller
      display-name: v1.0.0

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    #    enable-host: false
    #    enable-host-text: 192.168.0.193:8000
#    enable-home-custom: true
#    home-custom-path: classpath:md/home.md
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 珠海横乐医学科技有限公司 allen.huang@hanglok-tech.cn
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: true
    enable-group: true
  cors: false
  production: false
  basic:
    enable: true
    username: hanglok
    password: hanglok8888