#!/bin/bash

### BEGIN INIT INFO
# Provides:          imp-pacs
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: IMP-PACS
# Description:       Image Manager Platform PACS Service
### END INIT INFO

NAME=imp-pacs
USER=root
PIDFILE=/var/run/imp-pacs.pid
LOGFILE=/var/log/imp/imp-pacs.log

mainClass="cn.hanglok.pacs.ImpApplication"
cp=/etc/imp/pacs/dependency/*:/etc/imp/pacs/pacs-service.jar
SPRING_CONFIG_PARAM=-Dspring.config.location=classpath:application.yml,/etc/imp/pacs/pacs.yml
EXEC="/usr/bin/java -cp $cp $SPRING_CONFIG_PARAM $mainClass"

set -e

stop() {
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
    fi
    echo -n "Stopping $NAME: "
    if [ $PID ]; then
        kill $PID || true
        rm $PIDFILE || true
        echo "$NAME stopped."
    else
        echo "$NAME doesn't seem to be running."
    fi
}

start() {
    if [ -f $PIDFILE ]; then
        echo "$NAME seems to be already running, we found pidfile $PIDFILE."
        exit 1
    fi
    echo -n "Starting $NAME: "
    start-stop-daemon --start --quiet --background --chuid $USER --make-pidfile --pidfile $PIDFILE \
        --exec /bin/bash -- -c "exec $EXEC < /dev/null >> $LOGFILE 2>&1"
    echo "$NAME started."
}

reload() {
    echo 'Not yet implemented.'
}

status() {
    status_of_proc -p $PIDFILE java "$NAME" && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  reload)
    reload
    ;;
  force-reload)
    reload
    ;;
  status)
    status
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload|status}" >&2
    exit 1
    ;;
esac

exit 0